# Generated by Django 3.2 on 2023-02-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meterbus', '0004_devicehandler_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterbusdevice',
            name='instrument_handler',
        ),
    ]
